# Copyright 2019 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Just start the discovery service, used for configuring all other services
# Extract the project version (x.y.z-REVISION etc.)
app:
  version: '@project.version@'

# Don't register with eureka as it isn't up yet
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false

manager:
  services:
    discovery-service:
      jar: discovery-service/target/discovery-service-${app.version}-exec.jar
      log: discovery-service.log
      err: discovery-service.err
